name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  IMAGE_NAME: oviplokos/nginx-diplom
  NAMESPACE: nginx-diplom
  DEPLOYMENT_NAME: nginx-diplom

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Docker tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
                 
  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files in the working directory
      run: |
        ls -la

    - name: Extract version from tag or commit message
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
        fi
        if [[ -z "$VERSION" ]]; then
          echo "No version found in the commit message or tag"
          exit 1
        fi
        VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
        echo "Using version: $VERSION"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Replace image tag in nginx.yaml
      run: |
        if [ ! -f /home/netology/kube-manifest/nginx.yaml ]; then
          echo "nginx.yaml not found in the current directory"
          exit 1
        fi
        sed -i "s|image: oviplokos/nginx-diplom:.*|image: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}|" /home/netology/kube-manifest/nginx.yaml 

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f /home/netology/kube-manifest/nginx.yaml
